Prompt user to accept new terms if new terms are available
Concordium/concordium-reference-wallet-ios pull request #121
Opened 2021-11-24 14:13 UTC by ruxandra-constantinescu

## Purpose

Ask the user to accept new T&C when they are updated
Fixes #99 

## Changes

- saving a hash of the terms and conditions when they are accepted
- compare saved hash of the terms with the hash of the current hash

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

2021-11-24 17:27 UTC, td202 requested changes

2021-11-24 17:27 UTC, td202 commented on ConcordiumWallet/Settings/AppSettings.swift
> +    + "termsAndConditionsScreen.terms38.details".localized
This seems like it could be annoying to keep updated when the terms change, if sections are added or removed. Would it be possible to combine this somehow with the existing code in `TermsAndConditionsViewController`? Or wouldn't it suffice to have a version number for the terms that is updated with each revision, and just check that?

2021-11-24 17:27 UTC, td202 commented on ConcordiumWallet/Settings/AppSettings.swift
> +    static var termsHash: String? {
Perhaps `acceptedTermsHash` would be more meaningful.

2021-11-24 19:01 UTC, ruxandra-constantinescu commented on ConcordiumWallet/Views/AccountsView/AccountsCoordinator.swift
> +    func displayNewTerms()
Not really :) I made it like this to match the createAccount. But it doesn't need to pass through MenuCoordinator, you are completely right. I just removed that.
I would, however, like to keep both newTermsAvailable and showNewTerms for code clarity

2021-11-24 19:02 UTC, ruxandra-constantinescu commented on ConcordiumWallet/Settings/AppSettings.swift
> +    + "termsAndConditionsScreen.terms38.details".localized
The version number would pose the same problem and we agreed with Android that we would do hash, not a version number. I extracted the method that generated the attributed string in a separate file and use that to get the string used for hashing. That should solve any issues regarding sync :)

2021-11-24 19:02 UTC, ruxandra-constantinescu commented on ConcordiumWallet/Settings/AppSettings.swift
> +    static var termsHash: String? {
updated :)

2021-11-25 09:46 UTC, td202 approved these changes

2021-11-25 10:41 UTC, merged