Don't show backup warning on fresh install
Concordium/concordium-reference-wallet-ios pull request #157
Opened 2022-01-26 14:35 UTC by kristiyandobrev

## Purpose

Currently the backup warning alert is shown after a fresh app install, which should not be the case

Relates to #147 

## Changes

* Made `hasRunBefore` a setting in `AppSettings` 
* Checking for `hasRunBefore` before showing the backup warning alert

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2022-01-26 18:48 UTC, ruxandra-constantinescu requested changes
It needs to be updated so that the Welcome back si not shown after creating accounts on a fresh install

2022-01-26 18:48 UTC, ruxandra-constantinescu commented on ConcordiumWallet/Views/MoreSection/VerifyIdsAndAccounts/SanityChecker.swift
> +                if AppSettings.lastKnownAppVersionSinceBackupWarning == nil, AppSettings.hasRunBefore {
hasRunBefore does not give any info about whether it comes from the login screen or from creating an account / import. Has run before is used only to know whether the app has ever been launched by a user and in case it hasn't clear all data that might be left from a previous install (keychain)
You can do it either by sending a param to the AppCoordinator.showMainTabbar depending on where it is being called from, or add a new app setting which you can set in LoginCoordinator.start based on the value of passwordCreated

2022-01-27 08:20 UTC, kristiyandobrev commented on ConcordiumWallet/Views/MoreSection/VerifyIdsAndAccounts/SanityChecker.swift
> +                if AppSettings.lastKnownAppVersionSinceBackupWarning == nil, AppSettings.hasRunBefore {
Thanks for pointing it. It makes sense. Although I have now fixed it a bit differently.

2022-01-27 08:40 UTC, ruxandra-constantinescu approved these changes

2022-01-27 08:41 UTC, merged