WalletConenct deeplink support
Concordium/concordium-reference-wallet-ios pull request #368
Opened 2023-10-06 09:01 UTC by prinshamlet

2023-10-06 11:56 UTC, prinshamlet commented on ConcordiumWallet/AppCoordinator.swift
> +                }
consider guarding it

2023-10-06 11:58 UTC, prinshamlet commented on ConcordiumWallet/AppDelegate.swift
>          } else {
do extra check

2023-10-24 14:35 UTC, orhoj requested changes

2023-10-24 14:35 UTC, orhoj commented on ConcordiumWallet/AppCoordinator.swift
> +        else if let requestId = queryItems.first(where: { $0.name == "requestId" })?.value,
What is this used for?

2023-10-25 10:06 UTC, prinshamlet commented on ConcordiumWallet/AppCoordinator.swift
> +        else if let requestId = queryItems.first(where: { $0.name == "requestId" })?.value,
I used it to diffrentiate between session proposal and request deep link for sake of debuging. I think  there's no use for these variables now, because the WalletConnectCoordinator listens for requests anyway. We could use it for checking if the correct request is currently displayed, but it's not super easy, so for now we can just give up on this.

2023-10-26 07:12 UTC, orhoj commented
To me the changes look good now, but I don't have an option to test it right now. I would like @bisgardo to check it out and try it before we merge it.

2023-10-26 09:08 UTC, bisgardo commented on ConcordiumWallet/AppDelegate.swift
> +        } else if url.absoluteString.starts(with: ApiConstants.walletConnectURI) {
Just verified that the scheme will open the app but not walletconnect.

2023-10-26 09:17 UTC, bisgardo commented on ConcordiumWallet/Views/WalletConnect/AccountSelect/WalletConnectAccountSelectView.swift
> +        }
If I do the same on the current testnet build, I get an error "Pairing with topic (...) already exist". Afterwards the same error occurs, so it isn't actually a new bug.

2023-10-26 09:28 UTC, prinshamlet commented on ConcordiumWallet/AppDelegate.swift
> +        } else if url.absoluteString.starts(with: ApiConstants.walletConnectURI) {
I think it should be 
```    static let walletConnectURI = "\(scheme)://wc"```

2023-10-26 09:30 UTC, bisgardo commented on ConcordiumWallet/AppDelegate.swift
> +        } else if url.absoluteString.starts(with: ApiConstants.walletConnectURI) {
Testnet needs to support two schemes. You can check against both or use a regex.

2023-10-26 09:38 UTC, bisgardo commented on ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
> +
?

2023-10-26 09:38 UTC, bisgardo commented on ConcordiumWallet/AppCoordinator.swift
> +            let walletConnectCoordinator = WalletConnectCoordinator(
Shouldn't we dismiss any existing WC coordinator first?

2023-10-26 09:54 UTC, bisgardo reviewed
Please add PR description.

2023-10-26 09:54 UTC, bisgardo commented on ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
> +        self.parentCoordinator = parentCoordinator
:smile:

2023-10-26 09:54 UTC, bisgardo commented on ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
> +                        self.nukeWalletConnectSessionsAndPairings()
```suggestion
                    }, dismissView: { [weak self] in
                        self?.navigationController.popViewController(animated: true)
                        self?.parentCoordinator?.dismissWalletConnectCoordinator()
                        self?.nukeWalletConnectSessionsAndPairings()
```

2023-10-26 10:09 UTC, bisgardo commented on ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
> +                self.presentError(with: "errorAlert.title".localized, message: err.localizedDescription)
missing a dismissal?

2023-10-26 11:13 UTC, bisgardo commented on ConcordiumWallet/AppCoordinator.swift
> +    }
Maybe this is a bit more explicit?

```suggestion
    func openWalletConnectAccountSelection(url: URL) {
        guard let queryItems = URLComponents(url: url, resolvingAgainstBaseURL: false)?.queryItems else {
            showErrorAlert(ViewError.simpleError(localizedReason: "WalletConnect URL format incorrect."))
            return
        }

        if let uriValue = queryItems.first(where: { $0.name == "uri" })?.value {
            getOrCreateWalletConnectCoordinator().start(with: uriValue)
        }
    }
    
    func getOrCreateWalletConnectCoordinator() -> WalletConnectCoordinator {
        if let c = childCoordinators.first(where: { $0 is WalletConnectCoordinator }) as? WalletConnectCoordinator {
            return c
        }
        let c = WalletConnectCoordinator(
            navigationController: navigationController,
            dependencyProvider: defaultProvider,
            parentCoordinator: self
        )
        childCoordinators.append(c)
        return c
    }
```

2023-10-26 11:13 UTC, bisgardo commented on ConcordiumWallet/AppCoordinator.swift
> +    }
But what if the user is already in the WC flow? Wouldn't it be better to close that flow first then? I.e. using `dismissWalletConnectCoordinator`.

2023-10-26 11:59 UTC, prinshamlet commented on ConcordiumWallet/AppCoordinator.swift
> +    }
hmm that would be the best approach correct

2023-10-26 12:02 UTC, bisgardo commented on ConcordiumWallet/AppCoordinator.swift
> +    }
In fact, if there is already a WC connection, we still get the duplicate account list. I then got into a state where the disconnect button no longer worked.

I think connecting via deep link while already connected might be enough of an edge case that we shouldn't worry about it, but it's worth checking if the other solution avoids the issue.

2023-10-26 12:05 UTC, bisgardo commented on ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
> +        Task {
Intentional to not use weak self?

2023-10-26 14:45 UTC, prinshamlet commented on ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
> +                self.presentError(with: "errorAlert.title".localized, message: err.localizedDescription)
added

2023-10-26 18:21 UTC, prinshamlet commented on ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
> +        Task {
overlooked

2023-10-27 08:43 UTC, bisgardo approved these changes
Seems to work :tada: !

2023-10-27 08:59 UTC, merged