Refactor identity creation process.
Concordium/concordium-reference-wallet-ios pull request #61
Opened 2021-09-28 11:33 UTC by td202

## Purpose

This PR refactors identity creation so that identity and initial account objects are not created until the identity issuance flow is completed. Prior to this, temporary account objects are created as part of the identity issuance process, and account and identity objects are created before the issuance flow completes, which may cause them to show in the account list, even when they cannot be created.

This should give a more robust solution to #35 and should fix #53. It is possible this could help with #33, since the previous process could have led to confusion between accounts in some circumstances where the identity flow is interrupted and restarted. It may also help with #37, although more investigation is required there.

## Changes

- Introduce an `IdentityCreationEntity` that stores the details used for identity creation in the realm database before and during the interaction with the identity provider.
- Pass around the name used for the initial account prior to its creation rather than storing it with a temporary account in the realm.
- Create an `IdentityCreationEntity` immediately before invoking the identity provider, rather then creating an account and identity object at this point. This ensures that the account and identity aren't created prematurely. A UUID identifying the `IdentityCreationEntity` is added to the callback URL to ensure that there cannot be confusion about which identity is verified.
- Defer creating the initial account and identity until after the callback from the identity provider occurs, using the UUID to ensure that the correct account and identity objects are created.
- Rather than `CreatIdentityCoordinator` implementing `CreateNicknamePresenterDelegate` directly, define two separate wrapper classes that are used for when the account name and identity name are chosen. These wrappers maintain stateful information in a type-safe way.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2021-09-30 11:40 UTC, kristiyandobrev requested changes
I would also suggest rebasing onto the latest `main` branch.

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Service/MobileWallet.swift
> +final class IdentityCreation {
I think it would be a good idea if that class gets a file of it's own.

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Service/MobileWallet.swift
> +    let id = NSUUID().uuidString
You might replace `NSUUID` (Objc implementation) with `UUID` (Swift implementation)

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Service/MobileWallet.swift
> +                .tryMap { (pwHash) in
Since you are in a closure you and you reference `self` down below you need to capture it weakly: 

```suggestion
                .tryMap { [weak self] (pwHash) in
```

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Service/MobileWallet.swift
> +                                                            storageManager: self.storageManager)
Since you capture the `self` weakly it becomes optional:

```suggestion
                                                            storageManager: self?.storageManager)
```

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift
> +        navigationController.dismiss(animated: true) {
```suggestion
        navigationController.dismiss(animated: true) { [weak self] in
```

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift
> +            self.showIdentitySubmitted(identity: newIdentity, account: newAccount)
```suggestion
            self?.showIdentitySubmitted(identity: newIdentity, account: newAccount)
```

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift
> +            navigationController.dismiss(animated: true) {
```suggestion
            navigationController.dismiss(animated: true) { [weak self] in
```

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift
> +                self.showFailedIdentityCreation(error: serverError)
```suggestion
                self?.showFailedIdentityCreation(error: serverError)
```

2021-09-30 11:40 UTC, kristiyandobrev commented on ConcordiumWallet/Views/Identities/CreateIdentity/IdentityProviderList/IdentityProviderListPresenter.swift
> +                wallet.createIdRequestAndPrivateData(initialAccountName: self.initialAccountName,
Weak self is needed above 👆

2021-09-30 12:43 UTC, td202 commented on ConcordiumWallet/Service/MobileWallet.swift
> +                .tryMap { (pwHash) in
I'm not convinced that this is necessary. (`self` was used previously without being captured weakly.) My understanding is that this is to avoid a retain cycle, leading to a memory leak. I think this cannot happen or doesn't matter for a couple of reasons:
1. `MobileWallet` does not retain the publisher itself, and the caller calls `sink` on the result, so eventually the closure should no longer be retained.
2. The `MobileWallet` instance is retained for the entire lifetime of the application. This means that a retain cycle involving it is irrelevant, since anything that is retained indefinitely by `MobileWallet` will be retained indefinitely whether or not it also retains `MobileWallet`.

On the other hand, `weak self` would mean that we would have to account for the (impossible) case where `self` becomes `nil`.

2021-09-30 13:32 UTC, kristiyandobrev commented on ConcordiumWallet/Service/MobileWallet.swift
> +                .tryMap { (pwHash) in
Ah, yeah. I forgot that `MobileWallet` is injected by the `ServicesProvider`. My bad, sorry 🙋🏻‍♂️

2021-10-06 11:39 UTC, kristiyandobrev approved these changes

2021-10-07 09:33 UTC, merged